// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpGFkZqzNjXS3fykUhsiSLVfp2cef8v30',
    appId: '1:893273858056:web:43fed9918ef83f5279b1bd',
    messagingSenderId: '893273858056',
    projectId: 'chrono-a57de',
    authDomain: 'chrono-a57de.firebaseapp.com',
    storageBucket: 'chrono-a57de.appspot.com',
    measurementId: 'G-TC355JX3TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKUWLcu3s-PShi5_bd2bMYsoD2zD5i0oI',
    appId: '1:893273858056:android:edd100979a72c14379b1bd',
    messagingSenderId: '893273858056',
    projectId: 'chrono-a57de',
    storageBucket: 'chrono-a57de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0I11O6je01vBOiSI708WNVUnWgAmVxNo',
    appId: '1:893273858056:ios:93009c9aa5274aca79b1bd',
    messagingSenderId: '893273858056',
    projectId: 'chrono-a57de',
    storageBucket: 'chrono-a57de.appspot.com',
    iosBundleId: 'com.example.chronocapsules',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0I11O6je01vBOiSI708WNVUnWgAmVxNo',
    appId: '1:893273858056:ios:93009c9aa5274aca79b1bd',
    messagingSenderId: '893273858056',
    projectId: 'chrono-a57de',
    storageBucket: 'chrono-a57de.appspot.com',
    iosBundleId: 'com.example.chronocapsules',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpGFkZqzNjXS3fykUhsiSLVfp2cef8v30',
    appId: '1:893273858056:web:89b5558e96671cde79b1bd',
    messagingSenderId: '893273858056',
    projectId: 'chrono-a57de',
    authDomain: 'chrono-a57de.firebaseapp.com',
    storageBucket: 'chrono-a57de.appspot.com',
    measurementId: 'G-PXHMQQPJJT',
  );
}
